project: sd-from-scratch # Insert wandb project name
batch_size: 2048
seed: 17
scale_schedule_ratio: 1.0
name: pexels-speed-test # Insert wandb run name
eval_first: false
algorithms:
  low_precision_groupnorm:
    attribute: unet
    precision: amp_fp16
  low_precision_layernorm:
    attribute: unet
    precision: amp_fp16
model:
  _target_: diffusion.models.models.stable_diffusion_2
  model_name: /mnt/CV_teamz/pretrained/stable-diffusion-2-1
  pretrained: false
  precomputed_latents: true
  encode_latents_in_fp16: true
  fsdp: true
  val_metrics:
    - _target_: torchmetrics.MeanSquaredError
  val_guidance_scales: []
  loss_bins: []
dataset:
  train_batch_size: ${batch_size}
  eval_batch_size: 1024 # Should be 8 per device
  train_dataset:
    _target_: diffusion.datasets.pexels.pexels.build_pexels_dataloader
    img_dataset_prefix: /mnt/CV_teamz/crawl_data/pexels
    json_list: /mnt/CV_teamz/users/qiming/dataset/pexels/meta_0501+0601.json
    petrel_conf_path: /mnt/CV_teamz/open_datasets/datasets/LAION-5b/config/petreloss.tmp.conf
    batch_size: ${batch_size}
    tokenizer_name_or_path: /mnt/CV_teamz/pretrained/stable-diffusion-2-1
    # tokenizer_name_or_path: stabilityai/stable-diffusion-2-base
    caption_drop_prob: 0.0
    resize_size: 256
    drop_last: true
    shuffle: true
    prefetch_factor: 8
    num_workers: 8
    persistent_workers: true
    pin_memory: true
  eval_dataset:
    _target_: diffusion.datasets.pexels.pexels.build_pexels_dataloader
    img_dataset_prefix: /mnt/CV_teamz/crawl_data/pexels
    json_list: /mnt/CV_teamz/users/qiming/dataset/pexels/meta_0501+0601.json
    petrel_conf_path: /mnt/CV_teamz/open_datasets/datasets/LAION-5b/config/petreloss.tmp.conf
    batch_size: 8
    tokenizer_name_or_path: /mnt/CV_teamz/pretrained/stable-diffusion-2-1
    resize_size: 256
    prefetch_factor: 4
    num_workers: 8
    persistent_workers: true
    pin_memory: true
optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  weight_decay: 0.01
scheduler:
  _target_: composer.optim.MultiStepWithWarmupScheduler
  t_warmup: 10000ba
  milestones:
    - 200ep
logger:
  wandb:
    _target_: composer.loggers.wandb_logger.WandBLogger
    name: ${name}
    project: ${project}
    group: ${name}
    host: api.wandb.ai
    token: 30e859c562557e3cb316b5863156a37c09569611
    mode: offline
callbacks:
  speed_monitor:
    _target_: composer.callbacks.speed_monitor.SpeedMonitor
    window_size: 10
  lr_monitor:
    _target_: composer.callbacks.lr_monitor.LRMonitor
  memory_monitor:
    _target_: composer.callbacks.memory_monitor.MemoryMonitor
  runtime_estimator:
    _target_: composer.callbacks.runtime_estimator.RuntimeEstimator
  optimizer_monitor:
    _target_: composer.callbacks.OptimizerMonitor
trainer:
  _target_: composer.Trainer
  device: gpu
  max_duration: 550000ba
  eval_interval: 10000ba
  device_train_microbatch_size: ~
  run_name: ${name}
  seed: ${seed}
  scale_schedule_ratio: ${scale_schedule_ratio}
  save_folder:  # Insert path to save folder or bucket
  save_interval: 10000ba
  save_overwrite: true
  autoresume: false
  fsdp_config:
    sharding_strategy: "SHARD_GRAD_OP"
